### PR TITLE
Oryol Samples

### PR DESCRIPTION
**Pull request by floooh**
This PR contains the current Oryol samples under emscripten/oryol_samples (original sample page here: http://floooh.github.io/oryol/) built with binaryen as wasm, wast and asm.js. This is the result of a straight emscripten build without custom html shell pages.

Test instructions are in the readme, all demos except hello.js need the emscripten browser module environment to run (the easiest way to test in the browser is simply to start a python web server in the emscripten/oryol_samples directory with 'python -m SimpleHTTPServer'.

One problem I'm seeing after updating binaryen and spidermonkey is that some samples fail to parse both in the Chrome Canary and Firefox Nightly build, e.g. Chrome has the following error when launching the Fractal demo:

```
Fractal.js:137 Uncaught WasmModule::Instantiate(): Compiling WASM function #1:<?> failed:Result = ExprI32ReinterpretF32[0] expected type f32, found ExprGetLocal of type f64 @+877
```

One question I have is how to handle updates to these demos:
- when should the samples be updated, I would guess at least after significant changes in the WebAssembly toolchain
- how should updates be triggered? I've wrapped most things into a 'fips verb' python script, but currently there are manual step at the end of the build (copy result into git repo, push changes...)

Do you expect that the samples need to be update once per week? Once per month?

That's all that I can think of for now, let me know what changes you want/need :)

### CODE REVIEW

**Comment by jfbastien** [comment]
Could you add a license file to the top of the folder?

**Comment by floooh** [comment]
Ok done, I copied the Oryol MIT license file.

**Comment by kripken** [comment]
Thanks!

We'll need to rebuild the wast to wasm files every time the binary format changes, which is all the time ;) Practically speaking we could do it on each milestone or so, points where all browsers can run the same binaries.

I wonder though if the files here aren't overkill - I don't think we'd be able to test all these separate programs. Perhaps we could reduce this to a shorter list, whose size is determined by overlap? That is, if different programs test different aspects of wasm, we should have those different programs, but if they test different html or webgl features, perhaps not.

**Comment by floooh** [comment]
Yes I think I can reduce the number down to 5..7 of the more complex demos which cover different code bases to get some variety (e.g. 2 UI demos for ImGui and TurboBadger, 2 audio demos with SoLoud and libmodplug, 2 of the more complex, general Oryol demos using WebGL, and I'd also like to add one or two physics and pathfindind demos to the mix.

**Comment by floooh** [comment]
Ok, I have reduced the number of samples to 5 with as much code diversity as possible across the samples.

**Comment by kripken** [comment]
Great, thanks!

Would be nice to edit settings to have squash commits in this repo. Who's an owner? I think @lukewagner created the repo for us?

**Comment by jfbastien** [comment]
Squash is enoabled. Merging.

**Comment by floooh** [comment]
Ok thanks! Now you just need to ping me when you need these updated. I propose you open a ticket in the Oryol project (https://github.com/floooh/oryol/issues) when you think the time is right to update the samples.

**Pull request merged**
