### PR TITLE
Updated Oryol samples to WebAssembly version 0x0B

### PR DESCRIPTION
**Pull request by floooh**
This PR updates the Oryol samples to WebAssembly version 0x0B (at least I think it's 0B, I checked the generated wasm hex dumps and the fifth byte is 0x0B instead of 0x0A).

The following tools branches have been used, all as of 01-Jul-2016
- emscripten incoming (b266a04f7fc561c3a7e1b9e8bd4e66f77d40779a)
- binaryen master (44290db4fc014c8e032fb61f95ca9805d2ce57bc)
- Spidermonkey from mozilla-central (changeset:   303345:fdcee57b4e4f)

PS: the emscripten shell.html file has changed to shell_minimal.html

### CODE REVIEW

**Comment by kripken** [comment]
lgtm, thanks!

**Comment by floooh** [comment]
Btw, if you notice that the wasm binaries are outdated just drop me a quick note and I'll try to update them ASAP :)

**Comment by kripken** [comment]
Cool :)

**Comment by titzer** [comment]
Thanks for doing that!

**Pull request merged**
